excluded:
- Pods
- StampytTests
- StampytUITests

disabled_rules:
 - trailing_whitespace
 - identifier_name

line_length:
 ignores_function_declarations: true
 ignores_comments: true
 warning: 210
 error: 250
